name: Sync Upstream

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/LibreSpark/LibreTV.git || git remote set-url upstream https://github.com/LibreSpark/LibreTV.git
          git fetch upstream

      - name: Reset to upstream/main
        run: |
          git reset --hard upstream/main

      - name: Force push to origin/main
        run: |
          git push origin main --force
